name: Scraping FBC

on:
  workflow_dispatch:

jobs:
  run-scraper:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Scraping FBC
        run: python scraping_fbc.py
