name: Scraping FBC

on:
  workflow_dispatch:

jobs:
  run-scraper:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Setup Chrome
      #  uses: browser-actions/setup-chrome@latest

      - name: Install Google Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libglib2.0-0 libnss3 libgconf-2-4 libfontconfig1 libx11-6 libx11-xcb1 libxcb-dri3-0 libxcb1 libxcomposite1 libxdamage1 libxext6 libxfixes3 libxrandr2 libxtst6 libcups2 libgbm1 libpangocairo-1.0-0 libpango-1.0-0 libasound2 libatk1.0-0 libatk-bridge2.0-0 libgtk-3-0
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Scraping FBC
        run: python scraping_fbc.py
