name: Scraping FBC

on:
  workflow_dispatch:

jobs:
  run-scraper:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      #- name: Setup Chrome
      #  uses: browser-actions/setup-chrome@latest

      - name: Install Google Chrome dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libnss3 \
            libdbus-glib-1-2 \
            libgtk-3-0 \
            libx11-xcb1 \
            libasound2t64 \
            libxtst6 \
            libxss1 \
            libgbm1
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run Scraping FBC
        run: python scraping_fbc.py
      
      - name: Upload debug screenshot
        #if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-artifacts
          path: |
            *.png
            *.html

